name: Python package

on: [push, pull_request]

jobs:
  build:
    # Verifiation de l'os et de la version de Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      # Installation des dependances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Verification du code
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --ignore=E203,E266,E501,W503,F403,F401,E402 -v
      # Execution des tests
      # - name: Test with pytest
      #   run: |
      #     pip install pytest
      #     pytest tests/*.py
      # Execution coverage
      - name: Generate Report
        run: |
          pip install coverage
          coverage run -m unittest
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v2
